# Generated by Django 3.2.9 on 2021-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='base_branch',
            field=models.CharField(max_length=256, verbose_name="the repository's base branch"),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='compare_branch',
            field=models.CharField(max_length=256, verbose_name='your branch (the compare branch)'),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
