# Generated by Django 3.2.9 on 2021-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211204_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='base_branch',
            field=models.CharField(max_length=32, verbose_name="the repository's base branch"),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='compare_branch',
            field=models.CharField(max_length=32, verbose_name='your branch (the compare branch)'),
        ),
    ]
